// Proto definition for API service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1-devel
// 	protoc        v3.6.1
// source: api.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AreaInfo_LocationType int32

const (
	AreaInfo_COUNTY  AreaInfo_LocationType = 0
	AreaInfo_STATE   AreaInfo_LocationType = 1
	AreaInfo_COUNTRY AreaInfo_LocationType = 2
)

// Enum value maps for AreaInfo_LocationType.
var (
	AreaInfo_LocationType_name = map[int32]string{
		0: "COUNTY",
		1: "STATE",
		2: "COUNTRY",
	}
	AreaInfo_LocationType_value = map[string]int32{
		"COUNTY":  0,
		"STATE":   1,
		"COUNTRY": 2,
	}
)

func (x AreaInfo_LocationType) Enum() *AreaInfo_LocationType {
	p := new(AreaInfo_LocationType)
	*p = x
	return p
}

func (x AreaInfo_LocationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AreaInfo_LocationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (AreaInfo_LocationType) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x AreaInfo_LocationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AreaInfo_LocationType.Descriptor instead.
func (AreaInfo_LocationType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3, 0}
}

type ListOfStates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country string   `protobuf:"bytes,1,opt,name=Country,proto3" json:"Country,omitempty"`
	States  []string `protobuf:"bytes,2,rep,name=States,proto3" json:"States,omitempty"`
}

func (x *ListOfStates) Reset() {
	*x = ListOfStates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfStates) ProtoMessage() {}

func (x *ListOfStates) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfStates.ProtoReflect.Descriptor instead.
func (*ListOfStates) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *ListOfStates) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ListOfStates) GetStates() []string {
	if x != nil {
		return x.States
	}
	return nil
}

//Is a list of countries, as strings. Does NOT return data on
//each country, that must be called explicitly, per country.
//This is in contrast to Counties.
type ListOfCountries struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Countries []string `protobuf:"bytes,1,rep,name=Countries,proto3" json:"Countries,omitempty"`
}

func (x *ListOfCountries) Reset() {
	*x = ListOfCountries{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfCountries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfCountries) ProtoMessage() {}

func (x *ListOfCountries) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfCountries.ProtoReflect.Descriptor instead.
func (*ListOfCountries) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *ListOfCountries) GetCountries() []string {
	if x != nil {
		return x.Countries
	}
	return nil
}

//Returns a list of Counties, and the data for each as type
//AreaInfo.
type ListOfCounties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country  string   `protobuf:"bytes,1,opt,name=Country,proto3" json:"Country,omitempty"`
	State    string   `protobuf:"bytes,2,opt,name=State,proto3" json:"State,omitempty"`
	Counties []string `protobuf:"bytes,3,rep,name=Counties,proto3" json:"Counties,omitempty"`
}

func (x *ListOfCounties) Reset() {
	*x = ListOfCounties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfCounties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfCounties) ProtoMessage() {}

func (x *ListOfCounties) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfCounties.ProtoReflect.Descriptor instead.
func (*ListOfCounties) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *ListOfCounties) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ListOfCounties) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ListOfCounties) GetCounties() []string {
	if x != nil {
		return x.Counties
	}
	return nil
}

type AreaInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnixTimeOfRequest uint64  `protobuf:"varint,1,opt,name=UnixTimeOfRequest,proto3" json:"UnixTimeOfRequest,omitempty"`
	Lat               float32 `protobuf:"fixed32,2,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Long              float32 `protobuf:"fixed32,3,opt,name=Long,proto3" json:"Long,omitempty"`
	Deaths            uint32  `protobuf:"varint,4,opt,name=Deaths,proto3" json:"Deaths,omitempty"`
	ConfirmedCases    uint32  `protobuf:"varint,5,opt,name=ConfirmedCases,proto3" json:"ConfirmedCases,omitempty"`
	TestsGiven        uint32  `protobuf:"varint,6,opt,name=TestsGiven,proto3" json:"TestsGiven,omitempty"`
	Recoveries        uint32  `protobuf:"varint,7,opt,name=Recoveries,proto3" json:"Recoveries,omitempty"`
	Incidentrate      float32 `protobuf:"fixed32,8,opt,name=Incidentrate,proto3" json:"Incidentrate,omitempty"`
}

func (x *AreaInfo) Reset() {
	*x = AreaInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AreaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaInfo) ProtoMessage() {}

func (x *AreaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaInfo.ProtoReflect.Descriptor instead.
func (*AreaInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *AreaInfo) GetUnixTimeOfRequest() uint64 {
	if x != nil {
		return x.UnixTimeOfRequest
	}
	return 0
}

func (x *AreaInfo) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *AreaInfo) GetLong() float32 {
	if x != nil {
		return x.Long
	}
	return 0
}

func (x *AreaInfo) GetDeaths() uint32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *AreaInfo) GetConfirmedCases() uint32 {
	if x != nil {
		return x.ConfirmedCases
	}
	return 0
}

func (x *AreaInfo) GetTestsGiven() uint32 {
	if x != nil {
		return x.TestsGiven
	}
	return 0
}

func (x *AreaInfo) GetRecoveries() uint32 {
	if x != nil {
		return x.Recoveries
	}
	return 0
}

func (x *AreaInfo) GetIncidentrate() float32 {
	if x != nil {
		return x.Incidentrate
	}
	return 0
}

var File_api_proto protoreflect.FileDescriptor

var file_api_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x22, 0x2f, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74,
	0x4f, 0x66, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x5c, 0x0a, 0x0e, 0x4c, 0x69, 0x73,
	0x74, 0x4f, 0x66, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x69, 0x65, 0x73, 0x22, 0xb6, 0x02, 0x0a, 0x08, 0x41, 0x72, 0x65, 0x61,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x11, 0x55, 0x6e, 0x69, 0x78, 0x54, 0x69, 0x6d, 0x65,
	0x4f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x11, 0x55, 0x6e, 0x69, 0x78, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x03, 0x4c, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x6f, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x04, 0x4c, 0x6f, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x65, 0x61, 0x74,
	0x68, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x44, 0x65, 0x61, 0x74, 0x68, 0x73,
	0x12, 0x26, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x43, 0x61, 0x73,
	0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x65, 0x64, 0x43, 0x61, 0x73, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x65, 0x73, 0x74,
	0x73, 0x47, 0x69, 0x76, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x54, 0x65,
	0x73, 0x74, 0x73, 0x47, 0x69, 0x76, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x52, 0x65,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x49, 0x6e, 0x63, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c,
	0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x74, 0x65, 0x22, 0x32, 0x0a, 0x0c,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06,
	0x43, 0x4f, 0x55, 0x4e, 0x54, 0x59, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x52, 0x59, 0x10, 0x02,
	0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData = file_api_proto_rawDesc
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_rawDescData)
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_goTypes = []interface{}{
	(AreaInfo_LocationType)(0), // 0: api.proto.AreaInfo.LocationType
	(*ListOfStates)(nil),       // 1: api.proto.ListOfStates
	(*ListOfCountries)(nil),    // 2: api.proto.ListOfCountries
	(*ListOfCounties)(nil),     // 3: api.proto.ListOfCounties
	(*AreaInfo)(nil),           // 4: api.proto.AreaInfo
}
var file_api_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOfStates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOfCountries); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOfCounties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AreaInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_rawDesc = nil
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
